name: Deploy to Azure VM

on:
  push:
    branches:
      - Release  # Triggers when pushing to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Deploy to Azure VM using Password
      run: |
        sshpass -p "Happysingh@happy1" ssh -o StrictHostKeyChecking=no user_mithil@4.186.57.254 << EOF
        cd /var/www/html/hostel-assist-web   # Navigate to your project directory on the VM
        git pull origin main       # Pull the latest changes from the repository
        # Add any other deployment commands here
        # ./deploy.sh
        EOF

