name: Deploy to Azure VM

on:
  push:
    branches:
      - Release  # Triggers when pushing to the 'Release' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Deploy to Azure VM using Password
      env:
        VM_USERNAME: "user_mithil"
        VM_PASSWORD: ${{ secrets.VM_PASSWORD }}
        VM_IP: "4.186.57.254"

      run: |
        echo "password is : "
        echo $VM_PASSWORD
        sshpass -p "$VM_PASSWORD" ssh -o StrictHostKeyChecking=no -t \$VM_USERNAME@$VM_IP << EOF
        cd /var/www/html/hostel-assist-web   # Navigate to your project directory on the VM
        git pull origin Release       # Pull the latest changes from the repository
        # Add any other deployment commands here
        # ./deploy.sh
        EOF
