name: Deploy to Azure VM

on:
  push:
    branches:
      - Release  # Triggers when pushing to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Deploy to Azure VM using Password
      run: |
        sshpass -p "${{ secrets.AZURE_VM_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.AZURE_VM_USERNAME }}@${{ secrets.AZURE_VM_IP }} << EOF
        cd /   # Navigate to your project directory on the VM
        git pull origin main       # Pull the latest changes from the repository
        # Add any other deployment commands here
        # ./deploy.sh
        EOF

